### ISSUE TITLE
캡쳐 속도에 관한 질문이 있습니다.

### ISSUE THREAD

**Issue by youngchan-kim** [ukayzm/opencv#1]
python face_classifier.py 0 -d -S 0.1
-S 0.1이하의 캡쳐속도를 얻으려면 어떻게 해야하나요?
-S 0.01등등으로 해봤더니 오류가 나옵니다.

python face_classifier.py 0 -d -S 0.1
-S How do I get a capture rate of less than 0.1?
I tried it with -S 0.01 and so on, and an error appears.

**Comment by ukayzm** [comment]
Hardware에서 지원하는 이하의 숫자를 넣으면 에러가 납니다.
그리고, 다음부터는 어떤 에러가 나는지도 같이 알려주세요.

**Comment by youngchan-kim** [comment]
답변 감사합니다. 

Traceback (most recent call last):
  File "face_classifier.py", line 256, in <module>
    if frame_id % frames_between_capture != 0:
ZeroDivisionError: integer division or modulo by zero
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-czu11tvl\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

이런 오류가 나옵니다. 
그럼 Hardware에서 지원하는 이하의 숫자라면 더 빠른 캡쳐의 속도나 인식의 속도를 얻을 수 있는 다른 방법은 없는 건가요?

**Comment by ukayzm** [comment]
네. 없습니다.

**Comment by ukayzm** [comment]
close
